# Generated by Django 4.0.5 on 2022-06-09 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_agent',
        ),
    ]
