# Generated by Django 4.0.5 on 2022-06-10 14:49

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('brand_type', model_utils.fields.StatusField(choices=[('Apple', 'Apple'), ('Acer', 'Acer'), ('Asus', 'Asus'), ('BlackBerry', 'BlackBerry'), ('Casper', 'Casper'), ('Dell', 'Dell'), ('Google', 'Google'), ('Huawei', 'Huawei'), ('Honor', 'Honor'), ('HomeTech', 'HomeTech'), ('HP', 'HP'), ('Lenovo', 'Lenovo'), ('LG', 'LG'), ('Microsoft', 'Microsoft'), ('Msi', 'Msi'), ('Monster', 'Monster'), ('Redmi', 'Redmi'), ('Samsung', 'Samsung'), ('Sony', 'Sony'), ('Toshiba', 'Toshiba'), ('Xiaomi', 'Xiaomi'), ('Other', 'Other')], default='Apple', max_length=100, no_check_for_status=True)),
                ('screen_diagonal_type', model_utils.fields.StatusField(choices=[('10', '10'), ('13', '13'), ('13.3', '13.3'), ('14', '14'), ('15', '15'), ('15.6', '15.6'), ('16', '16'), ('16.1', '16.1'), ('17.3', '17.3')], default='10', max_length=100, no_check_for_status=True)),
                ('ram_memory_type', model_utils.fields.StatusField(choices=[('1Gb', '1Gb'), ('2Gb', '2Gb'), ('3Gb', '3Gb'), ('4Gb', '4Gb'), ('6Gb', '6Gb'), ('8Gb', '8Gb'), ('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB')], default='1Gb', max_length=100, no_check_for_status=True)),
                ('has_hdd', models.BooleanField(default=False)),
                ('has_ssd', models.BooleanField(default=False)),
                ('memory_type', model_utils.fields.StatusField(choices=[('16Gb', '16Gb'), ('32Gb', '32Gb'), ('64Gb', '64Gb'), ('128Gb', '128Gb'), ('256Gb', '256Gb'), ('512Gb', '512Gb'), ('1TB', '1TB'), ('2TB', '2TB'), ('4TB', '4TB')], default='16Gb', max_length=100, no_check_for_status=True)),
                ('discrete_video_card', models.BooleanField(default=False)),
                ('graphic_card_type', model_utils.fields.StatusField(choices=[('1Gb', '1Gb'), ('2Gb', '2Gb'), ('3Gb', '3Gb'), ('4Gb', '4Gb'), ('6Gb', '6Gb'), ('8Gb', '8Gb'), ('16GB', '16GB'), ('32GB', '32GB')], default='1Gb', max_length=100, no_check_for_status=True)),
                ('guaranty', models.CharField(blank=True, max_length=124, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('brand_type', model_utils.fields.StatusField(choices=[('Samsung', 'Samsung'), ('Apple', 'Apple'), ('Xiaomi', 'Xiaomi'), ('Nokia', 'Nokia'), ('Reeder', 'Reeder'), ('General Mobile', 'General Mobile'), ('Oppo', 'Oppo'), ('Realme', 'Realme'), ('LG', 'LG'), ('Huawei', 'Huawei'), ('BlackBerry', 'BlackBerry'), ('POCO', 'POCO'), ('Casper', 'Casper'), ('TCL', 'TCL'), ('VESTEL', 'VESTEL'), ('LENOVO', 'LENOVO'), ('Alcatel', 'Alcatel'), ('Htc', 'Htc'), ('ZTE', 'ZTE'), ('Motorola', 'Motorola'), ('OnePlus', 'OnePlus'), ('Meizu', 'Meizu'), ('Honor', 'Honor'), ('Panasonic', 'Panasonic'), ('Turkcell', 'Turkcell'), ('Turk Telekom', 'Turk Telekom'), ('Syrox', 'Syrox'), ('Asus', 'Asus')], default='Samsung', max_length=100, no_check_for_status=True)),
                ('memory_type', model_utils.fields.StatusField(choices=[('8GB', '8GB'), ('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('512GB', '512GB'), ('1TB', '1TB')], default='8GB', max_length=100, no_check_for_status=True)),
                ('ram_memory_type', model_utils.fields.StatusField(choices=[('1GB', '1GB'), ('2GB', '2GB'), ('3GB', '3GB'), ('4GB', '4GB'), ('6GB', '6GB'), ('8GB', '8GB'), ('16GB', '16GB'), ('32GB', '32GB')], default='1GB', max_length=100, no_check_for_status=True)),
                ('dual_sim', models.BooleanField(default=False)),
                ('nfc', models.BooleanField(default=False)),
                ('face_id', models.BooleanField(default=False)),
                ('network', model_utils.fields.StatusField(choices=[('2G', '2G'), ('3G', '3G'), ('4G', '4G'), ('4.5G', '4.5G'), ('5G', '5G')], default='2G', max_length=100, no_check_for_status=True)),
                ('guaranty', models.CharField(blank=True, max_length=124, null=True)),
                ('change', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='SmartphoneImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='electronic/smartphone_images/')),
                ('smartphone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smartphone_images', to='electronics.smartphone')),
            ],
        ),
        migrations.CreateModel(
            name='LaptopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='electronic/laptop_images/')),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptop_images', to='electronics.laptop')),
            ],
        ),
    ]
