# Generated by Django 4.0.5 on 2022-06-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_address_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
